print("Completa la Historia")
dia = input("Escoge un dia")
lugar = input("Escoge un lugar de mexico")
persona = input(" Elige una persona con quien estar")
adjetivo = input("Elige un Adjetivo para ti ")
arma = input("Elige un arma")

print("------------------------------------------")
print(f"Hoy,el Dia {dia} en {lugar}")
print(f"Conociste a {persona} que intentaba cruzar un puente")
print(f"Se bueno con el parece ser {adjetivo} pero descuida no es malo")
print(f"Encontraste una {arma} deben matar al elfo que estorba en el puente")
print()
print(f"Pero {persona} decide no pelear y pedir permiso")
print(f"Fin los dejan pasar sin usar la {arma}")
print("------------------------------------------")